---

- name: yum update
  yum:
    name: '*'
    state: latest

- name: install dos2unix
  yum:
    name: dos2unix
    state: present

- name: Add network credentials file for mouting network drive
  copy:
    src: "{{ playbook_dir }}/roles/base/files/credentials"
    dest: /etc/samba/credentials
    owner: root
    group: root
    mode: '0600'

- name: Update the network config with a static IP
  copy:
    src: "{{ playbook_dir }}/roles/base/files/ifcfg-eth0"
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: '0644'

- name: daemon-reload to pick up config changes
  systemd:
    daemon_reload: yes

- name: Restart the network service to get the new IP
  systemd:
    name: network
    state: restarted

- name: Create network mount directory if it does not exist
  ansible.builtin.file:
    path: /mnt/scm
    state: directory
    mode: '0774'

# this must be install first: ansible-galaxy collection install ansible.posix
- name: Mount an CIFS network share
  ansible.posix.mount:
    src: //mediahub.kaden.khp/share/SCM
    path: /mnt/scm
    opts: credentials=/etc/samba/credentials,vers=2.0,uid=997,gid=994,_netdev,x-systemd.automount,rw,nounix,file_mode=0774,dir_mode=0774
    state: mounted
    fstype: cifs
    boot: yes
